### ISSUE TITLE
Update dev environment page for running yarn install

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches-docs#126]
#### describe the issue
The note at the end of [this page](https://arches.readthedocs.io/en/stable/creating-a-development-environment/) says to run yarn install from /arches.
This results in not finding the install lockfile and nothing happening.

#### solution

Per @robgaston, it should now be run from arches/arches/install.
Verified that this solves the problem.

**Comment by mradamcox** [comment]
Thanks @azaroth42. Really I'd say it should be run from the project though, so maybe that dev installation environment guide should go farther to instruct users to make a project. I haven't developed without a project for a long time, and I think it's better to get in the habit of always using one (because that's how Arches is meant to be used anyway).

**Comment by mradamcox** [comment]
@azaroth42 this is no longer an issue as the dev environment docs now recommend that a project is created (and yarn install is run automatically during that process).
