### ISSUE TITLE
Update .sh install scripts for Mac OS and Linux

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches-docs#149]
#### describe the issue

The existing install scripts were removed as part of the software dependencies update for v5 because they were out of date.

Original scripts:
- Mac: https://gist.github.com/jmunowitch/35eb1d20a0b9cbf86f4b0eb4b167d43a
- linux: https://github.com/archesproject/arches/blob/master/arches/install/ci_install/install_arches.sh

##### which release does this issue concern?

v5

**Comment by chiatt** [comment]
Completed

**Comment by mradamcox** [comment]
Hey guys, I just want to point out that in [this commit](https://github.com/archesproject/arches-docs/commit/ffe8849de17c4fbf5947388ae611f49dac6a901b), which I'm assuming was the one connected to this ticket, the linux script was removed even though we have updated it and it's current (I'm adding it back in). Also I'm not clear on why this ticket references the ci_install script, because that has nothing to do with the documentation. Maybe it was supposed to reference the linux setup script?
