### ISSUE TITLE
Clarify node.js installation in Requirements/Dependencies page

### ISSUE THREAD

**Issue by brubyx** [archesproject/arches-docs#275]
The Requirements/Dependencies page mentions node.js only as Yarn prerequisite for Windows users. When I tried to install Arches on Ubuntu, Yarn did not install node.js and I had to install it manually.
https://arches.readthedocs.io/en/stable/requirements-and-dependencies/

**Comment by brubyx** [comment]
Thank you @ekansa, I still find it misleading. This is the remark I asked to clarify:
> **Windows Use the .msi installer in the link above, but first install [Node.js](https://nodejs.org/)

Yarn do not install node.js also on other platforms but the remark seems to be specific for Windows installs.

**Comment by ekansa** [comment]
Thanks @brubyx !  Do you think something like this will be better?

"Please note:  You will need to install Node.js prior to installing yarn on all platforms, not just Windows."

**Comment by brubyx** [comment]
In my opinion this is much clearer. Thank you  @ekansa

**Comment by ekansa** [comment]
@brubyx I'm doing some more investigation of this, and it seems that there are a few complications here. The current documentation points to a stale method for installing Yarn (redirecting to here; https://classic.yarnpkg.com/en/docs/install#windows-stable). More current Yarn installation instructions say nothing specific to Windows: https://yarnpkg.com/getting-started/install

If I understand things correctly, Yarn installation currently works the same across different operating systems because it's all handled by the Node.js package manager. Do I have that correct?

**Comment by ekansa** [comment]
PS. This @brubyx here's my proposed revision: https://arches.readthedocs.io/en/node_yarn_7_3/requirements-and-dependencies/?highlight=node.js%20yarn#software-dependencies

**Comment by chiatt** [comment]
@ekansa I think your proposed solution really helps clarify the issue.

**Comment by brubyx** [comment]
@ekansa your revision is perfect.
For Ubuntu the install script seems to take care of everything correctly and this is what I see on my server:
$ yarn version check
  yarn version v1.22.19
$ node -v
  v16.17.1
