### ISSUE TITLE
Improve API guidance regarding the required parameters

### ISSUE THREAD

**Issue by ekansa** [archesproject/arches-docs#319]
#### describe the issue
[nicospor](https://github.com/nicospor) ran into trouble making GET requests to the Arches JSON API which did not include the `indent` parameter. It turns out that Arches seems to expect that parameter. This expectation should be made explicit in the documentation. 

##### please add links to existing docs or code (if relevant)
This closed issue discusses the apparent problem and the expectation for an `indent` parameter. 
https://github.com/archesproject/arches/issues/9256

##### which release does this issue concern?
Probably all?

**Comment by ekansa** [comment]
[@nicospor ](https://github.com/nicospor) I drafted a revision to the API documentation. Do you think I captured the expectation about the `indent` parameter properly? https://arches.readthedocs.io/en/api_json_7_3/api/?highlight=API%20indent#general-expectations-requesting-json

(cc @chiatt - you may want to verify I've got the indent expectations correctly described)

**Comment by nicospor** [comment]
Thanks @ekansa, the problem was that the requests I was making to the REST API were missing the `format` parameter, which is required, while the `indent` parameter seems to be optional (at least in version 6.2 that I'm using). 
This is indeed documented: https://arches.readthedocs.io/en/api_json_7_3/api/?highlight=API%20indent#get--resources-uuid-resource%20instance%20id, so it was an error on my part since I didn't read it correctly.

Maybe the documentation could specify that `format` is a required parameter, while `indent` is optional (again, I tested this only on 6.2). 

Also, the documentation for [version 6.2](https://arches.readthedocs.io/en/6.2/api/?highlight=api#get--resources-uuid-resource%20instance%20id) could include `arches-json` as a valid format value.

Many thanks.

**Comment by ekansa** [comment]
@nicospor! Excellent and thanks for the guidance. It looks like I got the required parameters backwards! :) I'll make an update shortly.

**Comment by chiatt** [comment]
Thanks @nicospor and @ekansa, actually neither parameter is required. By default the resources endpoint returns json-ld. The issue that @nicospor was seeing was probably to an error in transforming the data to the json-ld format. 

By adding the `json` format, the data was transformed into the "json" format rather than json-ld, avoiding the error.

**Comment by ekansa** [comment]
@chiatt Oh interesting! So did the default JSON-LD not work because there may have been no ontology? I'd like to include some specifics about what's expected here.

**Comment by nicospor** [comment]
Thank you @chiatt for the clarification. Indeed, the 500 error occurs both with no parameters and with `format=json-ld` (in our instance), so it would be indeed interesting to understand why this happens. In any case, the `arches-json` format, which the API returns correctly, seems to include ontology-related information, if I'm not mistaken.

**Comment by ekansa** [comment]
@nicospor and @chiatt I made the changes noting ontology expectations for JSON-LD in the API. So, I'm going to close this issue. If you think there need to be further updates, please do not hesitate to open a new ticket! :)
