### ISSUE TITLE
error in the "Creating a Development Environment" chapter

### ISSUE THREAD

**Issue by ydrea** [archesproject/arches-docs#321]
#### describe the issue

The following information in the "CSS (Basic)" paragraph is wrong:
"... create project.css in your project’s media directory like this: my_project/my_project/media/css/project.css".
 This approach works only if the project.css file is uploaded in the "my_project/my_project/**static**/css/project.css" path.

##### please add links to existing docs or code (if relevant)

https://arches.readthedocs.io/en/stable/creating-a-development-environment/#overwriting-core-arches-content

##### which release does this issue concern?

all

**Comment by ekansa** [comment]
@ydrea Thanks for flagging this issue! I'll make a PR for you to review shortly

**Comment by mradamcox** [comment]
@ekansa and @ydrea, actually, it is correct as written, you can tell because core Arches stores this file in `media` (https://github.com/archesproject/arches/blob/master/arches/app/media/css/project.css), and there is no `static` directory by default.

I think the confusion stems from the fact that when you are serving your static files through Apache or nginx, you need to run `python manage.py collectstatic` to copy *all* static assets into a single location, and I think by default this location may be named `static`.

So if you do have a `static` directory and change the `project.css` in there, it's true that you'll see these changes reflected in your site. However, next time you run `collectstatic`, your changes will be overwritten by whatever file is stored in `media/css/project.css`.

**Comment by ekansa** [comment]
@mradamcox Ah! OK I just asked about some of this in my PR: https://github.com/archesproject/arches-docs/pull/322

What would add some clarity to this? Perhaps your comment above?

**Comment by mradamcox** [comment]
Hopefully @ydrea can speak to this as well. 

I see that the information about `collectstatic` is a bit buried here: https://arches.readthedocs.io/en/stable/serving-arches-with-apache/ (see section 2). At the very least, a note at the end of this section: https://arches.readthedocs.io/en/stable/creating-a-development-environment/#templates-htm-and-js-js-intermediate would be helpful. Something like:

> If you are using the Django development server to view your app (`python manage.py runserver`), new CSS and JS files will be automatically inherited and used to render your app. However, if you are using a webserver like Apache or nginx, you will need to run `python manage.py collectstatic` to copy all of these assets into a single place. See more here (link to the apache docs section about collectstatic)

This is a standard Django paradigm, so it would be good to also (or perhaps instead?) link out to the official docs on it: https://docs.djangoproject.com/en/4.1/ref/contrib/staticfiles/#collectstatic, or perhaps how staticfiles are served during development: https://docs.djangoproject.com/en/4.1/howto/static-files/#serving-static-files-during-development

**Comment by ekansa** [comment]
@mradamcox @ydrea I just added a NOTE section that hopefully adds some clarity about what happens with collectstatic.

**Comment by ydrea** [comment]
resolved by pointing to the collectstatic procedure
